"""
pdf_export.py — Diagnoverse PDF Report Generator
Uses fpdf2 to produce a branded, clean PDF from the final agent state.
"""

from fpdf import FPDF
from datetime import datetime
import io


# ── Colour palette ──────────────────────────────────────────────
NAVY       = (10,  14,  26)
TEAL       = (0,  212, 170)
CORAL      = (255, 107, 107)
ORANGE     = (255, 167,  38)
GREEN      = (72,  199, 142)
PURPLE     = (130, 100, 235)
WHITE      = (255, 255, 255)
LIGHT_GREY = (240, 242, 248)
MID_GREY   = (160, 170, 190)
DARK_GREY  = (40,  48,  70)


def _safe_str(val) -> str:
    """Coerce any value to a printable latin-1 safe string."""
    if val is None:
        return ""
    s = str(val)
    return s.encode("latin-1", errors="replace").decode("latin-1")


class DiagnoversePDF(FPDF):
    # ── Header ────────────────────────────────────────────────────
    def header(self):
        # Full page background
        self.set_fill_color(*NAVY)
        self.rect(0, 0, 210, 297, "F")

        self.set_font("Helvetica", "B", 14)
        self.set_text_color(*TEAL)
        self.set_xy(10, 4)
        self.cell(80, 10, "DIAGNOVERSE", ln=0)

        self.set_font("Helvetica", "", 8)
        self.set_text_color(*MID_GREY)
        self.set_xy(100, 4)
        self.cell(100, 10, "AI-Powered Medical Report Intelligence", ln=0, align="R")
        self.ln(18)

    # ── Footer ────────────────────────────────────────────────────
    def footer(self):
        self.set_y(-14)
        self.set_fill_color(*NAVY)
        self.rect(0, self.get_y(), 210, 20, "F")
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*MID_GREY)
        self.cell(0, 10,
                  f"Generated by Diagnoverse  |  {datetime.now().strftime('%d %b %Y, %I:%M %p')}  |  Page {self.page_no()}",
                  align="C")

    # ── Section heading ───────────────────────────────────────────
    def section_title(self, icon: str, title: str, color=PURPLE):
        self.ln(4)
        # Left accent bar
        self.set_fill_color(*color)
        self.rect(10, self.get_y(), 3, 8, "F")
        self.set_x(16)
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(*color)
        self.cell(0, 8, f"{title}", ln=True)
        self.ln(2)

    # ── Shaded card ───────────────────────────────────────────────
    def card_bg(self, h: float):
        x, y = self.get_x(), self.get_y()
        self.set_fill_color(*DARK_GREY)
        self.rect(10, y, 190, h, "F")

    # ── Bullet item ───────────────────────────────────────────────
    def bullet(self, text: str, color=TEAL, indent=14):
        self.set_x(indent)
        self.set_fill_color(*color)
        # Small circle bullet
        bx, by = self.get_x(), self.get_y() + 2.5
        self.ellipse(bx, by, 2, 2, "F")
        self.set_x(indent + 4)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*WHITE)
        self.multi_cell(182, 5, _safe_str(text))
        self.ln(1)

    # ── Horizontal rule ───────────────────────────────────────────
    def hr(self, color=DARK_GREY):
        self.set_draw_color(*color)
        self.set_line_width(0.3)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)


# ─────────────────────────────────────────────────────────────────
# Public entry-point
# ─────────────────────────────────────────────────────────────────

def generate_pdf(state: dict, file_name: str = "report") -> bytes:
    """
    Build a PDF from the final LangGraph state and return raw bytes
    so Streamlit can offer it as a download.
    """
    summary        = state.get("summary", {})
    medications    = state.get("medications", [])
    conditions     = state.get("conditions", [])
    lab_values     = state.get("lab_values", [])
    side_effects   = state.get("side_effects", [])
    drug_warnings  = state.get("drug_warnings", [])
    drug_inter     = state.get("drug_interactions", [])
    questions      = state.get("doctor_questions", [])

    pdf = DiagnoversePDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # ── Title block ──────────────────────────────────────────────
    pdf.set_y(22)
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(*WHITE)
    pdf.cell(0, 10, "Medical Report Summary", ln=True, align="C")

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*MID_GREY)
    pdf.cell(0, 6,
             f"File: {_safe_str(file_name)}   |   "
             f"Generated: {datetime.now().strftime('%d %b %Y, %I:%M %p')}",
             ln=True, align="C")
    pdf.ln(6)
    pdf.hr(DARK_GREY)

    # ══ 1. Overview ══════════════════════════════════════════════
    overview = summary.get("overview", "")
    if overview:
        pdf.section_title("📋", "Overview", TEAL)
        pdf.set_x(14)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*WHITE)
        pdf.multi_cell(182, 5, _safe_str(overview))
        pdf.ln(3)

    # ══ 2. Key Findings ══════════════════════════════════════════
    findings = summary.get("key_findings", [])
    if findings:
        pdf.section_title("🔍", "Key Findings", PURPLE)
        for f in findings:
            pdf.bullet(_safe_str(f), color=PURPLE)
        pdf.ln(2)

    # ══ 3. Lab Results Table ═════════════════════════════════════
    lab_table = summary.get("lab_table", [])
    if lab_table:
        pdf.section_title("🧪", "Lab Results", TEAL)

        # Table header
        col_w = [80, 50, 55]
        headers = ["Test", "Value", "Status"]
        header_colors = [DARK_GREY, DARK_GREY, DARK_GREY]

        pdf.set_font("Helvetica", "B", 9)
        pdf.set_x(10)
        for i, h in enumerate(headers):
            pdf.set_fill_color(*TEAL)
            pdf.set_text_color(*NAVY)
            pdf.cell(col_w[i], 7, h, border=0, fill=True, align="C")
        pdf.ln()

        # Table rows
        for idx, row in enumerate(lab_table):
            status = str(row.get("status", "")).strip().upper()
            status_color = GREEN if status == "NORMAL" else (CORAL if status == "HIGH" else ORANGE)

            fill = DARK_GREY if idx % 2 == 0 else (30, 36, 55)
            pdf.set_x(10)
            pdf.set_fill_color(*fill)
            pdf.set_text_color(*WHITE)
            pdf.set_font("Helvetica", "", 8)
            pdf.cell(col_w[0], 6, _safe_str(row.get("test", "")),  border=0, fill=True)
            pdf.cell(col_w[1], 6, _safe_str(row.get("value", "")), border=0, fill=True, align="C")
            # Status cell — coloured text
            pdf.set_text_color(*status_color)
            pdf.cell(col_w[2], 6, _safe_str(row.get("status", "")), border=0, fill=True, align="C")
            pdf.ln()
        pdf.ln(4)

    # ══ 4. Warnings ══════════════════════════════════════════════
    warnings = summary.get("warnings", [])
    if warnings:
        pdf.section_title("⚠️", "Warnings", CORAL)
        for w in warnings:
            pdf.bullet(_safe_str(w), color=CORAL)
        pdf.ln(2)

    # ══ 5. Recommendations ═══════════════════════════════════════
    recs = summary.get("recommendations", [])
    if recs:
        pdf.section_title("✅", "Recommendations", GREEN)
        for r in recs:
            pdf.bullet(_safe_str(r), color=GREEN)
        pdf.ln(2)

    # ══ 6. Questions for Your Doctor ═════════════════════════════
    if questions:
        pdf.section_title("❓", "Questions for Your Doctor", PURPLE)
        for i, q in enumerate(questions, 1):
            pdf.set_x(14)
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*TEAL)
            pdf.cell(6, 5, f"Q{i}.", ln=0)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(*WHITE)
            pdf.multi_cell(176, 5, _safe_str(q))
            pdf.ln(1)
        pdf.ln(2)

    # ══ 7. Drug Information ═══════════════════════════════════════
    has_drug_info = any([side_effects, drug_warnings, drug_inter])
    if has_drug_info:
        pdf.add_page()

        pdf.set_y(22)
        pdf.section_title("💊", "Drug Information", ORANGE)

        if medications:
            pdf.set_x(14)
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*MID_GREY)
            names = ", ".join(_safe_str(m.get("name", "")) for m in medications)
            pdf.multi_cell(182, 5, f"Medications detected: {names}")
            pdf.ln(3)

        # 3 subsections side by side (text, not columns — simpler for fpdf2)
        def drug_section(icon, title, items, color):
            if not items:
                return
            pdf.set_x(14)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*color)
            pdf.cell(0, 7, f"{title}", ln=True)
            for item in items:
                pdf.bullet(_safe_str(item), color=color)
            pdf.ln(2)

        drug_section("🩺", "Side Effects",     side_effects,  ORANGE)
        drug_section("⚠️",  "Drug Warnings",   drug_warnings, CORAL)
        drug_section("🔗", "Drug Interactions", drug_inter,   PURPLE)

    # ── Render to bytes ──────────────────────────────────────────
    buf = io.BytesIO()
    pdf_bytes = pdf.output()          # returns bytearray
    return bytes(pdf_bytes)
